
# Site settings
title: R3ID // Portfolio
email: info@r3id.io
description: > # this means to ignore newlines until "baseurl:"
  I believe in structured processes, clean design and excellent attention to detail.
  Problem-solving by delivering innovative solutions which are device-agnostic and
  accessible to as many visitors as possible through client collaboration.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://r3id.io" # the base hostname & protocol for your site
twitter_username: alr3id

# Build settings
markdown: kramdown
permalink: /blog/:title/

# Collection
collections:
  casestudy:
    title: Case study
    render: true
    output: true
