# Site Settings
baseurl: 		    ""
title: 			    R3ID

name: 			    R3ID
description: 	  Personal site for me!
url: 			      "http://localhost:4000"

paginate: 		  3
paginate_path: 	"blog/page:num"

email: 			    hello@r3id.io

disqus: 		    your_disqus_shortname
analytics: 	    UA-68933763-1

copyright: 		  Copyright &copy; 2016 R3ID.

# Build Settings
permalinks: 	  pretty

markdown:       kramdown
permalink:      /blog/:title/

collections:
  casestudy:
    title:      Case study
    render:     true
    output:     true

# Gems
gems:           [jekyll-paginate]
