title: R3ID
url: "https://r3id.io"
baseurl: /
google_analytics_key:

email:
description:  Test stuff.

# Build settings
paginate:       5
paginate_path:  "/blog/:num/"
permalink:      pretty

markdown:       kramdown
permalink:      /:title/

sass:
  style: compressed

plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

plugins:        [jekyll-paginate]
